# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'MetalImageDemo' do
  use_frameworks!
  pod 'MetalImage', :path => '../MetalImage.podspec', :subspecs => ['Core', 'ExtensionFilter']
end
